// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/ljxsteam/coinside-backend-kratos/app/team/service/config"
	"github.com/ljxsteam/coinside-backend-kratos/app/team/service/internal/data"
	"github.com/ljxsteam/coinside-backend-kratos/app/team/service/internal/server"
	"github.com/ljxsteam/coinside-backend-kratos/app/team/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(configConfig *config.Config) (*kratos.App, func(), error) {
	db := data.NewDB(configConfig)
	teamRepo := data.NewTeamRepoNoCache(db)
	teamService := service.NewUserService(teamRepo)
	grpcServer := server.NewGrpcServer(configConfig, teamService)
	registrar := server.NewRegistrar(configConfig)
	app := newApp(configConfig, grpcServer, registrar)
	return app, func() {
	}, nil
}
