trace:
  endpoint: http://127.0.0.1:14268/api/traces

server:
  addr: ":9002"
  name: "team-service"

zookeeper:
  address: "localhost:2181"
  timeout: 3

data:
  mariadb:
    host: "localhost"
    port: "3308"
    username: "ljx"
    password: "ljxljxljxljx"
    db_name: "coinside"