version: '3'

# service config in one docker-compose file for integrate test
# integrate test will start up service and samples test will depend on those containers
services:
  zookeeper:
    image: zookeeper
    expose:
      - 2181
    ports:
      - "2181:2181"
    restart: always
    networks:
      - app-network

  # User-Service
  userdb:
    image: mariadb:latest
    volumes:
      - userdb_data:/var/lib/mysql
      - ./app/user/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3305:3306"

  user-rpc:
    build:
      context: ./
      dockerfile: app/user/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - userdb

  # Card-Service
  carddb:
    image: mariadb:latest
    volumes:
      - carddb_data:/var/lib/mysql
      - ./app/card/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3307:3306"

  card-rpc:
    build:
      context: ./
      dockerfile: app/card/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - carddb

  # Team-Service
  teamdb:
    image: mariadb:latest
    volumes:
      - teamdb_data:/var/lib/mysql
      - ./app/team/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3308:3306"

  team-rpc:
    build:
      context: ./
      dockerfile: app/team/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - teamdb

  # Markdown-Service
  markdowndb:
    image: mariadb:latest
    volumes:
      - markdowndb_data:/var/lib/mysql
      - ./app/markdown/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3309:3306"

  markdown-rpc:
    build:
      context: ./
      dockerfile: app/markdown/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - markdowndb
  # Todo-Service
  tododb:
    image: mariadb:latest
    volumes:
      - tododb_data:/var/lib/mysql
      - ./app/todo/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3311:3306"
  todo-rpc:
    build:
      context: ./
      dockerfile: app/todo/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - tododb

  # Vote-Service
  votedb:
    image: mariadb:latest
    volumes:
      - votedb_data:/var/lib/mysql
      - ./app/vote/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3312:3306"
  vote-rpc:
    build:
      context: ./
      dockerfile: app/vote/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - votedb

  # attachment-Service
  attachmentdb:
    image: mariadb:latest
    volumes:
      -  attachmentdb_data:/var/lib/mysql
      - ./app/attachment/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3313:3306"
  attachment-rpc:
    build:
      context: ./
      dockerfile: app/attachment/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - attachmentdb

  # BFF
  bff-api:
    build:
      context: ./
      dockerfile: app/bff/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - user-rpc

networks:
  app-network:
    driver: bridge

volumes:
  userdb_data:
  carddb_data:
  teamdb_data:
  markdowndb_data:
  tododb_data:
  votedb_data:
  attachmentdb_data: