version: '3'

# service config in one docker-compose file for integrate test
# integrate test will start up service and samples test will depend on those containers
services:
  zookeeper:
    image: zookeeper
    expose:
      - 2181
    ports:
      - "2181:2181"
    restart: always
    networks:
      - app-network

  # User-Service
  userdb:
    image: mariadb:latest
    volumes:
      - userdb_data:/var/lib/mysql
      - ./app/user/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3306:3306"

  user-rpc:
    build:
      context: ./
      dockerfile: app/user/service/Dockerfile
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - userdb

  # Card-Service
  carddb:
    image: mariadb:latest
    volumes:
      - carddb_data:/var/lib/mysql
      - ./app/card/resource/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=ljxljxljxljx
      - MYSQL_DATABASE=coinside
      - MYSQL_USER=ljx
      - MYSQL_PASSWORD=ljxljxljxljx
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - "3307:3306"

  # BFF
  bff-api:
    build:
      context: ./
      dockerfile: app/bff/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always
    depends_on:
      - zookeeper
      - user-rpc

networks:
  app-network:
    driver: bridge

volumes:
  userdb_data:
  carddb_data: