// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/ljxsteam/coinside-backend-kratos/app/bff/internal/client"
	"github.com/ljxsteam/coinside-backend-kratos/app/bff/internal/controller"
	"github.com/ljxsteam/coinside-backend-kratos/app/bff/internal/router"
	"github.com/ljxsteam/coinside-backend-kratos/app/bff/internal/util"
	"github.com/ljxsteam/coinside-backend-kratos/pkg/config"
)

// Injectors from wire.go:

// initRouter init gin router.
func initRouter(conf *config.Config) *gin.Engine {
	discovery := client.NewZkDiscovery(conf)
	userClient := client.NewUserClinet(conf, discovery)
	userController := controller.NewUserController(userClient)
	cardClient := client.NewCardClinet(conf, discovery)
	teamClient := client.NewTeamClinet(conf, discovery)
	cardController := controller.NewCardController(userClient, cardClient, teamClient)
	attachmentClient := client.NewAttachmentClient(conf, discovery)
	attachmentController := controller.NewAttachmentController(attachmentClient)
	teamController := controller.NewTeamController(userClient, teamClient)
	voteClient := client.NewVoteClinet(conf, discovery)
	voteController := controller.NewVoteController(userClient, voteClient)
	todoServiceClient := client.NewTodoClinet(conf, discovery)
	todoController := controller.NewTodoController(userClient, todoServiceClient)
	markdownClient := client.NewMarkdownClinet(conf, discovery)
	markdownController := controller.NewMarkdownController(markdownClient)
	cosClient := util.NewCOSClinet(conf)
	objectController := controller.NewObjectController(cosClient)
	engine := router.NewApiRouter(conf, userController, cardController, attachmentController, teamController, voteController, todoController, markdownController, objectController)
	return engine
}
