trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  mariadb:
    host: "localhost"
    port: "3306"
    username: "ljx"
    password: "ljxljxljxljx"
    db_name: "coinside"