// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/ljxsteam/coinside-backend-kratos/app/card/service/config"
	"github.com/ljxsteam/coinside-backend-kratos/app/card/service/internal/data"
	"github.com/ljxsteam/coinside-backend-kratos/app/card/service/internal/server"
	"github.com/ljxsteam/coinside-backend-kratos/app/card/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(conf *config.Config) (*kratos.App, func(), error) {
	db := data.NewDB(conf)
	cardRepo := data.NewCardRepoNoCache(db)
	cardService := service.NewCardService(cardRepo)
	grpcServer := server.NewGrpcServer(conf, cardService)
	registrar := server.NewRegistrar(conf)
	app := newApp(conf, grpcServer, registrar)

	return app, func() {
	}, nil
}
