server:
  addr: ":8080"

zookeeper:
  address: "localhost:2181"
  timeout: 3

logger:
  file: "bff.log"

service:
  user:
    name: "user-service"

jwt:
  secret: "lab_web_jwt_secret"
  issuer: "fzusosdrock"
  expire_days: 14