server:
  addr: ":8080"

zookeeper:
  address: "zookeeper:2181"
  timeout: 3

logger:
  file: "bff.log"

service:
  user:
    name: "user-service"
  card:
    name: "card-service"
  team:
    name: "team-service"
  markdown:
    name: "markdown-service"
  todo:
    name: "todo-service"
  vote:
    name: "vote-service"
  attachment:
    name: "attachment-service"

cos:
  bucket: "{{ COS_BUCKET}}"
  region: "{{ COS_REGION }}"
  secret_id: "{{ COS_SECRET_ID }}"
  secret_key: "{{ COS_SECRET_KEY }}"

jwt:
  secret: "zRwhJ8AHxEBVx27uEivF5f6heZcz3g1Vtj60IT83Kwg"
  issuer: "ljxsteam"
  expire_days: 14