name: deploy to tencent cloud
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_KEY }}
            name: id_rsa # optional
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: rsync over SSH
        run: rsync -r ./ github@106.55.188.212:/home/github/coinside-backend/
