name: deploy to tencent cloud
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        run: echo  "${{ secrets.SSH_KEY }}" >> SSH_RAS
      - name: cat
        run: cat SSH_RAS
      - name: rsync over SSH
        run: rsync  -e "ssh -i SSH_RAS" -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/coinside-backend/
